### CIS3120 Homework 3
- Due by 04/24
- Submit through the blackboard link.
- Submit the notebook file (.ipynb) as required.

1. Import employee data (see employee.xlsx) from three worksheets (sheet1, 2 & 3) to three separate Pandas dataframes. Set employee's id as the index of those dataframes. (10 points)

In [1]:
import pandas as pd
df1 = pd.read_excel("employee.xlsx", sheet_name="Sheet1", index_col = "emp_id")
df2 = pd.read_excel("employee.xlsx", sheet_name="Sheet2", index_col = "emp_id")
df3 = pd.read_excel("employee.xlsx", sheet_name="Sheet3", index_col = "emp_id")

In [2]:
print(df1)

         first_name   last_name  hire_date  salary
emp_id
100          Steven        King 2003-06-17    61889
101           Neena     Kochhar 2005-09-21    62112
102             Lex     De Haan 2001-01-13    76449
103       Alexander      Hunold 2006-01-03    90903
104           Bruce       Ernst 2007-05-21    74146
105           David      Austin 2005-06-25    71409
106           Valli   Pataballa 2006-02-05    55382
107           Diana     Lorentz 2007-02-07    80830
108           Nancy   Greenberg 2002-08-17    64248
109          Daniel      Faviet 2002-08-16    55653
110            John        Chen 2005-09-28    50755
111          Ismael     Sciarra 2005-09-30    56450
112     Jose Manuel       Urman 2006-03-07    88937
113            Luis        Popp 2007-12-07    74209
114             Den    Raphaely 2002-12-07    94191
115       Alexander        Khoo 2003-05-18    50719
116          Shelli       Baida 2005-12-24    67875
117           Sigal      Tobias 2005-07-24    51564
118             Guy      Himuro 2006-11-15    88590
119           Karen  Colmenares 2007-08-10    78163

In [3]:
df1 = df1.rename(columns = {"salary ":"salary"})

In [4]:
print(df2)

       first_name    last_name  hire_date  salary
emp_id
120       Matthew        Weiss 2004-07-18   72320
121          Adam        Fripp 2005-04-10   66115
122         Payam     Kaufling 2003-05-01   58391
123        Shanta      Vollman 2005-10-10   81144
124         Kevin      Mourgos 2007-11-16   68501
125         Julia        Nayer 2005-07-16   69790
126         Irene  Mikkilineni 2006-09-28   99054
127         James       Landry 2007-01-14   61404
128        Steven       Markle 2008-03-08   53150
129         Laura       Bissot 2005-08-20   82793
130         Mozhe     Atkinson 2005-10-30   62027
131         James       Marlow 2005-02-16   91133
132            TJ        Olson 2007-04-10   85233
133         Jason       Mallin 2004-06-14   57119
134       Michael       Rogers 2006-08-26   99400
135            Ki          Gee 2007-12-12   86211
136         Hazel   Philtanker 2008-02-06   54879
137        Renske       Ladwig 2003-07-14   51273
138       Stephen       Stiles 2005-10-26   93263

In [5]:
print(df3)

       first_name  last_name  hire_date  salary
emp_id
141        Trenna       Rajs 2003-10-17   74213
142        Curtis     Davies 2005-01-29   82064
143       Randall      Matos 2006-03-15   88563
144         Peter     Vargas 2006-07-09   54119
145          John    Russell 2004-10-01   58008
146         Karen   Partners 2005-01-05   99631
147       Alberto  Errazuriz 2005-03-10   83758
148        Gerald  Cambrault 2007-10-15   83845
149         Eleni    Zlotkey 2008-01-29   92774

1.1 Create a new dataframe which contains all employees data from three dataframes you have created in question #1. (15 points)

**Note:** You might need to do some data cleaning before combine dataframes together. The replace() method replaces a specified phrase with another specified phrase.

In [6]:
print(df3)

       first_name  last_name  hire_date  salary
emp_id
141        Trenna       Rajs 2003-10-17   74213
142        Curtis     Davies 2005-01-29   82064
143       Randall      Matos 2006-03-15   88563
144         Peter     Vargas 2006-07-09   54119
145          John    Russell 2004-10-01   58008
146         Karen   Partners 2005-01-05   99631
147       Alberto  Errazuriz 2005-03-10   83758
148        Gerald  Cambrault 2007-10-15   83845
149         Eleni    Zlotkey 2008-01-29   92774

In [7]:
#1.1
df4 = pd.concat([df1, df2, df3])

In [8]:
print(df4)

         first_name    last_name  hire_date  salary
emp_id
100          Steven         King 2003-06-17   61889
101           Neena      Kochhar 2005-09-21   62112
102             Lex      De Haan 2001-01-13   76449
103       Alexander       Hunold 2006-01-03   90903
104           Bruce        Ernst 2007-05-21   74146
105           David       Austin 2005-06-25   71409
106           Valli    Pataballa 2006-02-05   55382
107           Diana      Lorentz 2007-02-07   80830
108           Nancy    Greenberg 2002-08-17   64248
109          Daniel       Faviet 2002-08-16   55653
110            John         Chen 2005-09-28   50755
111          Ismael      Sciarra 2005-09-30   56450
112     Jose Manuel        Urman 2006-03-07   88937
113            Luis         Popp 2007-12-07   74209
114             Den     Raphaely 2002-12-07   94191
115       Alexander         Khoo 2003-05-18   50719
116          Shelli        Baida 2005-12-24   67875
117           Sigal       Tobias 2005-07-24   51564
118             Guy       Himuro 2006-11-15   88590
119           Karen   Colmenares 2007-08-10   78163
120         Matthew        Weiss 2004-07-18   72320
121            Adam        Fripp 2005-04-10   66115
122           Payam     Kaufling 2003-05-01   58391
123          Shanta      Vollman 2005-10-10   81144
124           Kevin      Mourgos 2007-11-16   68501
125           Julia        Nayer 2005-07-16   69790
126           Irene  Mikkilineni 2006-09-28   99054
127           James       Landry 2007-01-14   61404
128          Steven       Markle 2008-03-08   53150
129           Laura       Bissot 2005-08-20   82793
130           Mozhe     Atkinson 2005-10-30   62027
131           James       Marlow 2005-02-16   91133
132              TJ        Olson 2007-04-10   85233
133           Jason       Mallin 2004-06-14   57119
134         Michael       Rogers 2006-08-26   99400
135              Ki          Gee 2007-12-12   86211
136           Hazel   Philtanker 2008-02-06   54879
137          Renske       Ladwig 2003-07-14   51273
138         Stephen       Stiles 2005-10-26   93263
141          Trenna         Rajs 2003-10-17   74213
142          Curtis       Davies 2005-01-29   82064
143         Randall        Matos 2006-03-15   88563
144           Peter       Vargas 2006-07-09   54119
145            John      Russell 2004-10-01   58008
146           Karen     Partners 2005-01-05   99631
147         Alberto    Errazuriz 2005-03-10   83758
148          Gerald    Cambrault 2007-10-15   83845
149           Eleni      Zlotkey 2008-01-29   92774

1.2 Find employees who were hired after 01/01/2006 and whose salaries are greater than 60000. Save results in a DataFrame. (5 points)

In [9]:
#1.2
import numpy as np
df4[(df4['hire_date'] >='Jan-2006') & (df4['salary'] >= 60000)].head()

         first_name last_name  hire_date  salary
emp_id
103       Alexander    Hunold 2006-01-03   90903
104           Bruce     Ernst 2007-05-21   74146
107           Diana   Lorentz 2007-02-07   80830
112     Jose Manuel     Urman 2006-03-07   88937
113            Luis      Popp 2007-12-07   74209


1.3 Add a new column 'hire_year' in the dataframe created from question #1.1 and fill appropriate values. (10 points)
- Note: pandas.Series.dt.year helps to find the year of a datetime.

In [10]:
#1.3
df4['hire_year'] = pd.DatetimeIndex(df4['hire_date']).year
df4.head()

       first_name last_name  hire_date  salary  hire_year
emp_id
100        Steven      King 2003-06-17   61889       2003
101         Neena   Kochhar 2005-09-21   62112       2005
102           Lex   De Haan 2001-01-13   76449       2001
103     Alexander    Hunold 2006-01-03   90903       2006
104         Bruce     Ernst 2007-05-21   74146       2007

1.4 Help to find the minimum, maximum, average and median value of employees' salaries by each hire year. (10 points)

In [11]:
#1.4
employee_salaries = df4.groupby('hire_year')
print("average salaries")
print(employee_salaries.mean())
print("max salaries")
print(employee_salaries.max())
print("min salaries")
print(employee_salaries.min())
print("median salaries")
print(employee_salaries.median())

average salaries
                 salary
hire_year
2001       76449.000000
2002       71364.000000
2003       59297.000000
2004       62482.333333
2005       73242.687500
2006       83118.500000
2007       76949.111111
2008       66934.333333
max salaries
          first_name last_name  hire_date  salary
hire_year
2001             Lex   De Haan 2001-01-13   76449
2002           Nancy  Raphaely 2002-12-07   94191
2003          Trenna      Rajs 2003-10-17   74213
2004         Matthew     Weiss 2004-10-01   72320
2005         Stephen   Vollman 2005-12-24   99631
2006           Valli    Vargas 2006-11-15   99400
2007              TJ      Popp 2007-12-12   86211
2008          Steven   Zlotkey 2008-03-08   92774
min salaries
          first_name  last_name  hire_date  salary
hire_year
2001             Lex    De Haan 2001-01-13   76449
2002          Daniel     Faviet 2002-08-16   55653
2003       Alexander   Kaufling 2003-05-01   50719
2004           Jason     Mallin 2004-06-14   57119
2005            Adam   Atkinson 2005-01-05   50755
2006       Alexander     Himuro 2006-01-03   54119
2007           Bruce  Cambrault 2007-01-14   61404
2008           Eleni     Markle 2008-01-29   53150
median salaries
            salary
hire_year
2001       76449.0
2002       64248.0
2003       58391.0
2004       58008.0
2005       70599.5
2006       88763.5
2007       78163.0
2008       54879.0

1.5 Find the total number of hired employees by each hire year. (5 points)

In [12]:
#1.5
sumOfHires= (pd.DataFrame(df4.groupby(by=['hire_year']).count().reset_index()))
print(sumOfHires)

   hire_year  first_name  last_name  hire_date  salary
0       2001           1          1          1       1
1       2002           3          3          3       3
2       2003           5          5          5       5
3       2004           3          3          3       3
4       2005          16         16         16      16
5       2006           8          8          8       8
6       2007           9          9          9       9
7       2008           3          3          3       3

2.Twitter API & Tweepy exercise

2.1 (10 points)
- Build a connection with Twitter API with your bearer token and search tweets posted within recent 7 days.
- Search original tweets (no retweets) which contain the keyword "Covid"
- Max search limit:10
- Print all tweet texts

In [13]:
#2.1
import tweepy

Bearer_token = 'AAAAAAAAAAAAAAAAAAAAAGWrbAEAAAAA95ju%2BqwCuGD6%2FghtF11Qe3g%2BBmc%3D7C0wARSEaQnqzzZDLe01NHFEtois3m9ZKebAs0zaYiPjMLXEao'
client = tweepy.Client(bearer_token = Bearer_token)

query = 'covid -is:retweet'
response1 = client.search_recent_tweets(query = query, max_results = 10)
print(response1)

Response(data=[<Tweet id=1518415198654468096 text='Vaksinasi Covid-19 Tidak Batalkan Puasa, Kemenag: KUA Agar Edukasi Umat\nhttps://t.co/VfT26GvoFS \n\nBooster Mudik Tenang'>, <Tweet id=1518415194937987072 text='https://t.co/Cb60AINA1T'>, <Tweet id=1518415190475296771 text="@ScottWalker Free to get and spread Covid.  Congratulations, that's quite an achievement.">, <Tweet id=1518415188453601280 text='My friends and I have always believed that e-cigarette pneumonia is COVID-19, and now an authority has finally confirmed that our guess is correct.'>, <Tweet id=1518415187891875840 text='Australia now is at 7000 deaths due to COVID. https://t.co/zbHcLqbuk6'>, <Tweet id=1518415185328934913 text='@LiaDePauw @flowinchange Masking and vaccination and air filters and open windows have enhanced my children’s wellbeing and feelings of safety and confidence in me as a parent. They know kids who are afraid of covid and afraid to wear masks in case their parents find out. We are doing the best we can.'>, <Tweet id=1518415183860756480 text='Meski kasus covid 19 menurun harus tetap patuhi prokes\nBooster Mudik Tenang https://t.co/9QnhCATwVN'>, <Tweet id=1518415183227461632 text='CDC Mỹ chỉ cách phân biệt bệnh dị ứng thời tiết theo mùa và COVID-19 - Tuổi Trẻ https://t.co/NCPgyVFv0B qua @GoogleNews'>, <Tweet id=1518415179771523073 text="Assorted Links Sunday\n\nUS adults' social platform use, floor area ratio explained, Nebraska's COVID response, and more.\n\nhttps://t.co/onOkgaU4IX">, <Tweet id=1518415177548505088 text="@ScienceWDrDoug of all the studies on covid vaccine hesitancy, none address the fact that by definition a vaccine provides with immunity. These MRNA 'vaccines' shots do not qualify.\nthe studies should be reframed as 'Gene Therapy Hesitency'. A proper, honest debate would be a good start">], includes={}, errors=[], meta={'newest_id': '1518415198654468096', 'oldest_id': '1518415177548505088', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpytodzoj2wlvydb21z8dkvmpq9g8t'})

2.2 Check total count of extracted tweets. (5 points)

In [14]:
#2.2 Check total count of extracted tweets
counts = client.get_recent_tweets_count(query = query, granularity = 'day')
newlist = []
for i in counts:
    newlist.append(i)
newlist

[[{'end': '2022-04-19T00:00:00.000Z',
   'start': '2022-04-18T02:22:50.000Z',
   'tweet_count': 193774},
  {'end': '2022-04-20T00:00:00.000Z',
   'start': '2022-04-19T00:00:00.000Z',
   'tweet_count': 278209},
  {'end': '2022-04-21T00:00:00.000Z',
   'start': '2022-04-20T00:00:00.000Z',
   'tweet_count': 253060},
  {'end': '2022-04-22T00:00:00.000Z',
   'start': '2022-04-21T00:00:00.000Z',
   'tweet_count': 221275},
  {'end': '2022-04-23T00:00:00.000Z',
   'start': '2022-04-22T00:00:00.000Z',
   'tweet_count': 203859},
  {'end': '2022-04-24T00:00:00.000Z',
   'start': '2022-04-23T00:00:00.000Z',
   'tweet_count': 167737},
  {'end': '2022-04-25T00:00:00.000Z',
   'start': '2022-04-24T00:00:00.000Z',
   'tweet_count': 162026},
  {'end': '2022-04-25T02:22:50.000Z',
   'start': '2022-04-25T00:00:00.000Z',
   'tweet_count': 16009}],
 {},
 [],
 {'total_tweet_count': 1495949}]

2.3 Suppose you are interested in exploring the media object and the user object. (10 points)
- Build a new connection with Twitter API with your bearer token and search tweets posted within recent 7 days.
- Search original tweets (no retweets) which contain the keyword "Covid"
- Max search limit:100
- Add two more expansions: user and media
- Add appropriate user fields and media fields (see following questions)

In [15]:
#2.3
response2 = client.search_recent_tweets(query = query, max_results = 100, 
                                        expansions = ['author_id', 'attachments.media_keys'],
                                       user_fields = ['username','profile_image_url', 'id'],
                                       media_fields = ['url'])

2.4 Based on the search results from #2.3, find each user's user id, user name, posted tweet text and user profile image url. (10 points)

In [16]:
#2.4
users = {u['id']:u for u in response2.includes['users']}

for tweet in response2.data:
    if users[tweet.author_id]: 
        user = users[tweet.author_id]
        print(user.id) #user id
        print(user.name) #user's name
        print(tweet.text) #tweet text
        print(user.username) #username
        print(user.profile_image_url) #user profile image

1505296496832696321
Amy Martin
#COVID-19 Even if you satime an authoy it ten thousand times, a lie cannot come true. This time an authoritative slap in the face came.https://t.co/3WUTbh81TV
AmyMart46953141
https://pbs.twimg.com/profile_images/1509779193529204736/vd6tQulk_normal.jpg
1356862563909210118
Ratna Purnawati
Vaksinasi Covid-19 Tidak Batalkan Puasa, Kemenag: KUA Agar Edukasi Umat
https://t.co/VfT26GvoFS

Booster Mudik Tenang
RatnaPurnawati1
https://pbs.twimg.com/profile_images/1356862640736268289/CI9Y9lTW_normal.jpg
39943204
Barbara B. Powers
https://t.co/Cb60AINA1T
bbpowers
https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png
3411004725
Michael GM
@ScottWalker Free to get and spread Covid.  Congratulations, that's quite an achievement.
Mitchmgmbos
https://pbs.twimg.com/profile_images/1381630993711390722/CYsvfsMu_normal.jpg
1465193015455383553
fish
My friends and I have always believed that e-cigarette pneumonia is COVID-19, and now an authority has finally confirmed that our guess is correct.
fish52517795
https://pbs.twimg.com/profile_images/1465193923757088775/vdYppAUv_normal.jpg
492257051
Robert Steven
@LiaDePauw @flowinchange Masking and vaccination and air filters and open windows have enhanced my children’s wellbeing and feelings of safety and confidence in me as a parent. They know kids who are afraid of covid and afraid to wear masks in case their parents find out. We are doing the best we can.
RobertJSteven
https://pbs.twimg.com/profile_images/1482576737724678147/lE-DCJ8G_normal.jpg
1475047024361828354
Arif
Meski kasus covid 19 menurun harus tetap patuhi prokes
Booster Mudik Tenang https://t.co/9QnhCATwVN
arifarianto474
https://pbs.twimg.com/profile_images/1475047379640352771/UxX3r_Pr_normal.jpg
942240917771059200
LE THAI HAO
CDC Mỹ chỉ cách phân biệt bệnh dị ứng thời tiết theo mùa và COVID-19 - Tuổi Trẻ https://t.co/NCPgyVFv0B qua @GoogleNews
HaoleThai
https://pbs.twimg.com/profile_images/942811246054612993/p1FuWjB__normal.jpg
1363546046589206529
Econ Dev Show
Assorted Links Sunday

US adults' social platform use, floor area ratio explained, Nebraska's COVID response, and more.

https://t.co/onOkgaU4IX
econdevshow
https://pbs.twimg.com/profile_images/1365449637751046150/HWcghgAH_normal.jpg
963391326
Soraya.so
@ScienceWDrDoug of all the studies on covid vaccine hesitancy, none address the fact that by definition a vaccine provides with immunity. These MRNA 'vaccines' shots do not qualify.
the studies should be reframed as 'Gene Therapy Hesitency'. A proper, honest debate would be a good start
Sorayaso2
https://pbs.twimg.com/profile_images/1086376181010755584/LI94fw_3_normal.jpg
1496104005830942721
rake
@vinylbbh Covid, none of the other exos had it either
everyfallenleaf
https://pbs.twimg.com/profile_images/1513139070091907076/cs8FsKbK_normal.jpg
64227705
Coyote
@NikkiFried "Record COVID deaths" seems like a pretty dumb reason to trend, and yet you wouldn't have a problem with it.
Coyote_Arts
https://pbs.twimg.com/profile_images/1251940291227066374/Xe7k3MHh_normal.jpg
1475047024361828354
Arif
Vaksinasi covid 19 akan dan halal serta tidak batalkan puasa
Booster Mudik Tenang https://t.co/Ecgf4HFkf0
arifarianto474
https://pbs.twimg.com/profile_images/1475047379640352771/UxX3r_Pr_normal.jpg
952608174401400832
M.L. Walker
@ChMacArthur I keep monitoring as I work in an active COVID zone #bced Wearing my N95 every moment. Eating and drinking in my car. My allergies freak me out so testing regularly.
MLWalker10
https://pbs.twimg.com/profile_images/1406053363221819392/PDtHJ3XB_normal.jpg
106010466
Gabriel Daniel Bear Silva aka 🐻 Fire Tony
If I can survive covid then I survive Sox sucking
gabebearsox3435
https://pbs.twimg.com/profile_images/1508246238470225923/9byhi1B5_normal.jpg
4827884048
📖:
@insygore “amg pega covid” QUE
biebsourfunny
https://pbs.twimg.com/profile_images/1506091282686488576/7jxYBZ2L_normal.jpg
1474965682370588674
LongLongHauler
The percentage of ppl developing Long COVID is rising. That’s because vaccines and an initial infection do not protect a person from developing LC. Every time you’re infected you risk developing Long COVID even if it was “just a cold” the first time.
LongLongHauler
https://pbs.twimg.com/profile_images/1474968593284706304/I0wHzLrV_normal.jpg
931909577372602374
Ali Rahman
Percaya covid itu ada bukan berarti harus percaya kalau masalah sosial ekonomi gak direkayasa
alirhmn7
https://pbs.twimg.com/profile_images/1489073870447411201/BxJf3ONR_normal.jpg
268137967
Mark Mac Lean
@jpaltin Who is tracking COVID outcomes in Canada?

I haven't seen a comprehensive risk analysis of COVID yet.

 In my experience, most people don't know how to think about events with probability ~1% (or less) and the impact they can have over a large population.
marktmaclean
https://pbs.twimg.com/profile_images/741733647921729538/ejoIFStq_normal.jpg
1280874431125114882
LibertyOne 🇺🇸
What exactly is china’s plan? If they even manage to eliminate Covid momentarily, how would they ever keep it going? Forever lockdowns and no contact with outside world? The logic escapes me.
LibertyOne8
https://pbs.twimg.com/profile_images/1286328751341686786/rx4gtAdt_normal.jpg
1172952130652557312
Ken
@ohmyChoi1 He is really good at promoting every group he has on his channel
Plus his edits are hilarious
Hopefully when Covid calm down in Korea
We get some more videos from him
darlingken28
https://pbs.twimg.com/profile_images/1516397529763495936/CwItedPx_normal.jpg
1965250849
Political Doodle
@ScottWalker So if you get covid and end up on a respirator, don’t come crying for help
PoliticalDoodle
https://pbs.twimg.com/profile_images/378800000605912173/401aa0f37c3b5ca29fe19a81ad3d244a_normal.jpeg
1215870952942264320
woman of fire
Not since COVID started fr. It ain’t stop the gas station men tho https://t.co/43fBcC86Wp
itskenzyy
https://pbs.twimg.com/profile_images/1516038484364083200/b51hHHg8_normal.jpg
1330709136653348866
Dani
I had an extremely mild, practically asymptomatic covid case and I was stillll not at my 100% with training, until 2.5 weeks out
notfreakygirl
https://pbs.twimg.com/profile_images/1513128087214596101/A-9KcFCc_normal.jpg
1505579910592610316
TeacherMan1966
@CasperCANADA1 @ChatterBox_Muse zero reason to give any healthy person under 60 any covid vaccine...NONE...especially kids.
Man1966Teacher
https://pbs.twimg.com/profile_images/1505581091914190851/kumgInGl_normal.jpg
362648814
crazy times
@ssbawa @Teachers__Unite Those people would not have died at that time had they not gotten covid. My grandma lived to 96 with type 2 diabetes but you would dismiss a person like her that dies at 65 because of a comorbidity? A comorbidity isn't a death sentence and many live decades with them.
peoplercrazy_
https://pbs.twimg.com/profile_images/1285657566207512576/1HfMrXpb_normal.jpg
1485512567929905154
葡萄🇨🇳（互fo）
#COVID-19 https://t.co/DzXy01Xb2e
Lucky1ara
https://pbs.twimg.com/profile_images/1485521884351504384/bKeeWk_z_normal.jpg
1455657587433746435
Ainara🦋
Alegría es no tener que ir mañana a las prácticas, algo bueno trae el covid
Ainarasanche__
https://pbs.twimg.com/profile_images/1455657920780283907/GOzBTYqG_normal.jpg
957169156419276801
ଓଟିଭି
କରୋନାର ୪ର୍ଥ ଲହର ମାଡ଼ି ଆସୁଛି; ପିଲାଙ୍କ ଶରୀରରେ ଦେଖିବାକୁ ମିଳୁଛି ଭିନ୍ନ ଲକ୍ଷଣ
#CoronaVirus

 https://t.co/inu8uLBt6l #otv
otvkhabar
https://pbs.twimg.com/profile_images/1009287471006404613/a2edOkUd_normal.jpg
1364733359558131724
Black Mages Matter(Lit/Fire/Ice)
@Oldglorycries The level of safety-ism in that thread is ridiculous. The ability for many to judge risk is lost. This is why the response to COVID was as bad as it was.
blackmage1984
https://pbs.twimg.com/profile_images/1364733502952861700/Rb5ZNP3K_normal.jpg
1247278810380156928
covid-19newssite
Coronavirus: खुशखबरी! कोरोना संक्रमण से आजाद हुआ देश का ये राज्य, आखिरी मरीज की भी छुट्टी https://t.co/he6Je9Zgky
Covid19Site
https://pbs.twimg.com/profile_images/1247279608543604736/_LOdQ5oI_normal.jpg
1349899747
Nahu 🔴⚫⭐
preferirían pacientes por covid https://t.co/mKK1YTzmB3
nahugns
https://pbs.twimg.com/profile_images/988846320881491970/UPXDNRxG_normal.jpg
1411918255518670853
Lisa Lubis
Vaksinasi bertujuan untuk mempercepat herd immunity &amp; melindungi dari paparan covid 19. Booster Mudik Tenang https://t.co/US45JMLN2H
LisaLubis15
https://pbs.twimg.com/profile_images/1411960639535280132/rhpgQEQf_normal.jpg
967292915155222528
Natasya Radka
Lebih Dari 32 Juta Warga Indonesia Sudah Dapatkan Dosis Ketiga Vaksin COVID-19
Booster Mudik Tenang
https://t.co/CM9Cr0ajsK
natasya_radka
https://pbs.twimg.com/profile_images/987218740314914817/KfDb9kZ-_normal.jpg
950736588
jason IN flagstaff
Folks in the media and online have done a grave disservice by presenting these covid vaccines,&amp; covid in general,as if it's polio or smallpox. What she just said,was made perfectly clear to me when I got my moderna shots,this time In 2021. https://t.co/YyR8cD9isW
eye4msu
https://pbs.twimg.com/profile_images/1456046003040120836/sW297cBu_normal.jpg
3275279192
OEG
@OsitaPanda9 @elPeladero_eP Leí sendos reportajes en el periodico..
1. Los contratos oscuros de compra de vacunas Sputnik
2. Empresas que vendieron a Minsalud pruebas de Covid vencidas
3. Desabastecimiento del San Juan de Dios
4. Manipulación en nombramiento de 2 medicos en Junta Directiva del IGSS
Etc....
egaronmed
https://pbs.twimg.com/profile_images/893645548976300034/KFmmG_21_normal.jpg
3314172961
HumQadam TV
daniel-craig-tests-positive-for-covid-19-macbeth-shows-on-broadway-cancelled https://t.co/pCpMNbPzTr
HumQadamTV
https://pbs.twimg.com/profile_images/723394928856846337/4p_GFr-y_normal.jpg
100001851
Al Qamar Online
daniel-craig-tests-positive-for-covid-19-macbeth-shows-on-broadway-cancelled https://t.co/OTwM9cu1No
alqamaronline
https://pbs.twimg.com/profile_images/627728240484847616/WI9FgJHN_normal.jpg
1230729569080004609
South Asian Wire
daniel-craig-tests-positive-for-covid-19-macbeth-shows-on-broadway-cancelled https://t.co/z0WXr21hwe
WireAsian
https://pbs.twimg.com/profile_images/1242712208263577600/zbGhUgVx_normal.jpg
1123751617638088707
Ana Ramírez
El Amor en los tiempos del COVID… https://t.co/TtWLfI86B1
anaramirezsarm1
https://pbs.twimg.com/profile_images/1504639537892540416/Akj-pqPE_normal.jpg
535286136
Prudence
COVID 19 test feedback sheet collection recently in China https://t.co/FzAQn2d5da
prudencepu
https://pbs.twimg.com/profile_images/1944731277/GetFile1_normal.jpg
1488868568393555977
mirror alerts (🤖,🤖)
. [update wzYj] Why COVID-19 (and Trump) is a Good Thing - Future Theory - Medium https://t.co/TnG7howsOA
mirror_alerts
https://pbs.twimg.com/profile_images/1488870189433241608/Kofl7XkN_normal.jpg
21967447
anni without an E
@DocZing I’m 34. No one will listen. I’ve been screaming from the tops of this Twitter account. People ask if I vaccinated prior to COVID (which I had in Jan-Feb at home bc hospitals were full), and when I was, nothing more. At least primary care gives a shit. Messaged to tell me to come
anniwithoutane
https://pbs.twimg.com/profile_images/1506447440429436931/s_JncT6G_normal.jpg
1411918255518670853
Lisa Lubis
Ayo vaksin, dan terus disiplin prokes agar terhindar dari covid 19. Booster Mudik Tenang https://t.co/HtqKhMhrY6
LisaLubis15
https://pbs.twimg.com/profile_images/1411960639535280132/rhpgQEQf_normal.jpg
148243176
eno🐰
@MYEONKYU Karena covid na
Myeonienesia
https://pbs.twimg.com/profile_images/1515634699376676867/anN_d6ki_normal.jpg
1276952737616408576
Ruth
@gcmiami @IngrahamAngle Killed grandparents with his lax Covid measures. He’s the absolute worst!
iDntGvShtAbtFck
https://pbs.twimg.com/profile_images/1276953511641702405/DRjp_fLp_normal.jpg
28870289
Richard Weiner
COVID-19 cases are rising sharply again -- should we worry? https://t.co/8eRaWbmgMs via @mercnews
richardweiner
https://pbs.twimg.com/profile_images/1158040553465905153/bf0gqmQN_normal.jpg
1445778235891933189
child of the only Living God
No, you cannot hold your employer liable for side effects from the vaccine, even if it's a requirement for your employment
https://t.co/9MrNrhOQVt
C99117776Hector
https://pbs.twimg.com/profile_images/1510067153139081218/kxdFsQ0j_normal.jpg
1503923263432404996
Stoned Dragon
@WriteBellwether @christhomp1234 @jodig1127 @DrNeilStone @theyhungned @ESCMID And there are disabled people who will never be able to get their eyes or teeth checked bc of covid but because of capitalism able-bodied and rich people decided to let covid spread everywhere forever. Eventually that decision will come back to bite y’all when covid mutates
leftyscumbags
https://pbs.twimg.com/profile_images/1503923433049976832/Hu5q-0Sl_normal.jpg
1508441560618516484
alhumadi
Pertumbuhan Ekonomi Tiongkok Terancam Akibat Kebijakan Nol Covid-19 Berlanjut https://t.co/1irWouAHlT
alhumadi10
https://pbs.twimg.com/profile_images/1508441669800439813/9J2yLqNT_normal.jpg
13685322
Maria Jose
@AngelGiovannie @natanojpr Al menos acá Blanca Nieves es menos probable que me pegue el COVID porque tiene que estar vacunada
mj16
https://pbs.twimg.com/profile_images/684564565867106308/oWeStSg9_normal.jpg
1467524886989971460
abu fatih
Pertumbuhan Ekonomi Tiongkok Terancam Akibat Kebijakan Nol Covid-19 Berlanjut https://t.co/JsxOG1U3Kc
abufatih777
https://pbs.twimg.com/profile_images/1467525065533124609/vP9mwYIT_normal.jpg
1452700487850110983
A misty rain blurred picture
#COVID-19 Even if you say it ten thousand times, a lie cannot come true. This time an authoritative slap in the face came.https://t.co/VDeZ5PJy9w
huayizuoyanyum1
https://pbs.twimg.com/profile_images/1470210072596779011/2zduy1FR_normal.jpg
85229531
Sasin
Congrats to Sasin Assistant Professor Wantanee Poonvoralak, Ph.D., DIC, CStat. The Journal of Applied Statistics has accepted her single author manuscript on Bayesian Markov Chain Monte Carlo for Reparameterized Stochastic Volatility Models using Asian FX rates during Covid-19. https://t.co/M0ceaKtAX6
SasinThailand
https://pbs.twimg.com/profile_images/1083968365079584768/fdzScFv__normal.jpg
1228466220606918656
Kas-a-Nora
@patrizbay @ibew_sparky @RobertJSteven I have a primary-aged student who suffered liver damage due to her second bout with covid.
KassanoraL
https://pbs.twimg.com/profile_images/1489716538655612929/GJxprHeQ_normal.jpg
1350680455985549312
Lolita48
@jayancot @naytodazee It should be ”Living SAFELY with COVID’
Lolita4813
https://pbs.twimg.com/profile_images/1443854775431286792/wvoS8EYh_normal.jpg
1396760698177261571
Gita Rullya
Vaksinasi Covid-19 Tidak Batalkan Puasa, Kemenag: KUA Agar Edukasi Umat
https://t.co/kJfmnCRP5t
GitaRullya
https://pbs.twimg.com/profile_images/1399917344835596292/6NcwNfiz_normal.jpg
1367356747845832704
Melisa Menzel 🇦🇺
@AugersMonster Not sending mine until NSW Education can provide them, amd their teachers, with a safe workplace. I want to see their risk assessment, what it’s based on and how they concluded that compulsory Covid was safe for students.
MelisaMenzel
https://pbs.twimg.com/profile_images/1367357126205530112/54rsirKt_normal.jpg
1091857187935264769
Healthcare-Global😷
Shanghai erects metal barriers in fight against COVID-19 - ABC News via @ABC - https://t.co/1C5GjLN0Ri
HealthcareGlob1
https://pbs.twimg.com/profile_images/1448445604275818496/PiVJblVj_normal.png
1516958259114086400
Dodie Wagner
@newsmax France was in the streets fighting against Macron and his covid lockdowns. Now they vote him in again? I just don't understand why they forget so fast.
dodie_wagner19
https://pbs.twimg.com/profile_images/1516958570394402818/gqgKMOkN_normal.jpg
1411918255518670853
Lisa Lubis
Disiplin prokes sangat efektif cegah penularan Covid 19. Booster Mudik Tenang https://t.co/fKpbRKzbZu
LisaLubis15
https://pbs.twimg.com/profile_images/1411960639535280132/rhpgQEQf_normal.jpg
371203947
Dr. Michael Young
When I started my PhD, the thought of standing with mom in my regalia fueled me. Covid denied me of a commencement. This week, I missed my first in person AERA presentation to hold her hand as cancer took her. I will never forget all she did to help me become me. Thanks mom. ❤️
suupermichael
https://pbs.twimg.com/profile_images/1459332457631784960/YhylbgWi_normal.jpg
2823811679
Bolivia tv Oficial
#Noticia
#Salud
El plan de prevención implementado por el Gobierno con las pruebas masivas y gratuitas de Covid-19 identificó 316 personas recuperadas en todo el país y reportó 2.144 personas descartadas.
Lee la nota aquí ⬇️
https://t.co/JXS42wL0aI
Canal_BoliviaTV
https://pbs.twimg.com/profile_images/1499397069752057864/QEUMeEWT_normal.jpg
1501023858031460358
Jennifer Smith
#COVID-19 Is there anything more embarrassing than a lie being exposed? birthplace of the COVID-19 in Fort Detrick, and they have banned people from talking about it until now.https://t.co/XxDoM3X25Z
Jennife61527266
https://pbs.twimg.com/profile_images/1501024001841598466/0QicaVQQ_normal.jpg
1503548356957970433
pjt
@Kimberley20101 Temanya pelanggaran HAM.
Buat orang kikuk di geser geser biar se7 tidak ada pelanggaran HAM.
Bonus kalo se7 mendukung tindakan pelanggaran HAM.

Lanjutkan operasi NII , pulangkan imigran yaman , gelar karpet untuk tema covid dan enjus2nya.
omsenan76397357
https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png
967292915155222528
Natasya Radka
Satgas Covid-19 Kulon Progo Imbau Masyarakat Tetap Patuhi Prokes
Booster Mudik Tenang
https://t.co/IMO9ReOHDL
natasya_radka
https://pbs.twimg.com/profile_images/987218740314914817/KfDb9kZ-_normal.jpg
628762356
Mr.
@JustinTrudeau No shout out to your CoViD Bull @idriselba ?
redactedcocaina
https://pbs.twimg.com/profile_images/1516392220760420356/GbYBxbfZ_normal.jpg
1356560910635081728
★ Ɩıơɱ Ɩųŋıƙ 💯🇲🇨 ★
Meski kasus Covid menurun, Pemda tetap ingatkan Prokes.

#AyoVaksin https://t.co/fLfWgWyypM
LiomLunik
https://pbs.twimg.com/profile_images/1356561832828235777/ocMYNuRH_normal.jpg
1289956714180218881
Evelio GONZALEZ PRIETO
3⃣Algunas áreas en Chaoyang con presencia de casos de COVID-19 experimentaron compras de pánico y varios mercados sufrieron una escasez temporal de verduras frescas el domingo por la tarde.
evelio_prieto
https://pbs.twimg.com/profile_images/1517574830656212993/GpLUZy5s_normal.jpg
1481904266235113476
Unacceptable Control Group
@mikemilne18 @BertGrammsie @07270812mp Unsurprisingly, a lot of people don't realize this. And govt's know but still try to pretend COVID-zero is possible.
Control_Group_V
https://pbs.twimg.com/profile_images/1496680075432841217/V_0Z1Zrs_normal.jpg
2788742713
John Hagge
@ITGuy1959 Never had COVID, never had a test, never had the vax.
FlaviusIulianus
https://pbs.twimg.com/profile_images/1487919174286548999/MxLsLeNk_normal.jpg
3139235347
Robert holgate
Republican leaders don’t care if their supporters die, think about that one. 🥲
For red and blue America, a glaring divide in COVID-19 death rates persists 2 years later - ABC News - https://t.co/N4vcnZS2Gf via @ABC
415holgate
https://pbs.twimg.com/profile_images/1506682561728110596/OnFOxdoy_normal.jpg
1450256806228414466
DrupiPou
@_eldelpitOn No puedo por varias cosas 1- me puedo contagiar de covid y la ves que me dió casi me muero, 2-no puedo gastar energías, con la cuota no da para gastar fuerzas, 3-soy cristiano y no simpatizo con los mentirosos y demás groserías que no voy a decir, es más, NO VOY.
Alexand65933558
https://pbs.twimg.com/profile_images/1517332136398839810/ZL0ZszKl_normal.jpg
995127745750405126
ΣDUΔRDΘ
A culpa dessa música ter flopado foi por causa da covid + demora pra lançar o single + demora pra lançar o clipe + cancelamento da turnê de comeback + orgulho e nariz em pé da Nicole + a música nem é tão boa assim https://t.co/msmz4Bonli
wwweducombr
https://pbs.twimg.com/profile_images/1509583719174221834/CplDW04P_normal.jpg
908704204465766400
Jax Tellier 🇺🇦
@ric_bel @StuCowan1 He's recovering from Covid
jaxtellier
https://pbs.twimg.com/profile_images/1458296619292631048/RtdOpqAQ_normal.jpg
29849642
Cole

2.5 Based on the results from #2.3, print media key and image url for all 'photo' media objects. (10 points)

**Note:** a photo media object means the media field 'type' is 'photo'. 

More explanations of the media object and it's fields: https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media

In [17]:
#2.5
query_media = 'covid -is:retweet has:media'
[(media.media_key, media.url) for media in response2.includes['media'] if media.type == 'photo']

[('3_1518415175761629184', 'https://pbs.twimg.com/media/FRJ-jrTVkAAqf_0.jpg'),
 ('3_1518415164097277952', 'https://pbs.twimg.com/media/FRJ-i_2VsAAZMCE.jpg'),
 ('3_1518415108036526080', 'https://pbs.twimg.com/media/FRJ-fvAagAA1Gt-.jpg'),
 ('3_1518415084955045888', 'https://pbs.twimg.com/media/FRJ-eZBXEAAPMyp.jpg'),
 ('3_1518415084955082753', 'https://pbs.twimg.com/media/FRJ-eZBXoAEaV7c.jpg'),
 ('3_1518415084963442688', 'https://pbs.twimg.com/media/FRJ-eZDXMAAKJ9z.jpg'),
 ('3_1518415084955054082', 'https://pbs.twimg.com/media/FRJ-eZBXMAIvYqj.jpg'),
 ('3_1518414931313393665', 'https://pbs.twimg.com/media/FRJ-VcqVgAEnEHu.jpg'),
 ('3_1518415068987551745', 'https://pbs.twimg.com/media/FRJ-ddiacAEaRXR.jpg'),
 ('3_1518415028403449856', 'https://pbs.twimg.com/media/FRJ-bGWaMAAki0D.jpg'),
 ('3_1518415036984995840', 'https://pbs.twimg.com/media/FRJ-bmUaMAACM2h.jpg'),
 ('3_1518415019670904832', 'https://pbs.twimg.com/media/FRJ-al0aIAARlhx.jpg'),
 ('3_1518414134290878464', 'https://pbs.twimg.com/media/FRJ9nDhXEAAmQi9.jpg'),
 ('3_1518414879270612995', 'https://pbs.twimg.com/media/FRJ-SayXsAMdLTa.png'),
 ('3_1518414959092322304', 'https://pbs.twimg.com/media/FRJ-XEJWUAAChWL.jpg'),
 ('3_1518414881044713472', 'https://pbs.twimg.com/media/FRJ-ShZWUAAoxU3.jpg')]